services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - ZABBIX_API_TOKEN=${ZABBIX_API_TOKEN}
    networks:
      - grafana-net
      - homelab-net
    depends_on: []

networks:
  grafana-net:
  homelab-net:
    external: true

volumes:
  grafana-data: