/**
 * Hardcoded data for Satellite Stateboard
 * Design: Aerospace Command Center - Mission-critical operational data
 */

import type {
  Ship,
  Terminal,
  SatelliteLease,
  LeasePhase,
  OperationalNote,
} from "@/../../shared/types";

// Ship data from project requirements
export const SHIPS: Ship[] = [
  {
    id: "ship-001",
    name: "Aegis Refrain",
    class: 4,
    hullNumber: "AEG-001",
    description: "Multi-purpose research vessel",
  },
  {
    id: "ship-002",
    name: "Void Skimmer",
    class: 1,
    hullNumber: "VOI-001",
    description: "High-speed reconnaissance craft",
  },
  {
    id: "ship-003",
    name: "Harvester of Stars",
    class: 8,
    hullNumber: "HRV-001",
    description: "Large cargo and resource collection vessel",
  },
  {
    id: "ship-004",
    name: "Silent Prowler",
    class: 2,
    hullNumber: "SIL-001",
    description: "Stealth operations platform",
  },
  {
    id: "ship-005",
    name: "Titan's Reach",
    class: 10,
    hullNumber: "TIT-001",
    description: "Flagship command vessel",
  },
  {
    id: "ship-006",
    name: "Neon Dragonfly",
    class: 1,
    hullNumber: "NEO-001",
    description: "Agile scout vessel",
  },
  {
    id: "ship-007",
    name: "Gilded Horizon",
    class: 5,
    hullNumber: "GIL-001",
    description: "Diplomatic and exploration vessel",
  },
  {
    id: "ship-008",
    name: "Obsidian Maw",
    class: 7,
    hullNumber: "OBS-001",
    description: "Heavy combat platform",
  },
  {
    id: "ship-009",
    name: "Calamity's Wake",
    class: 9,
    hullNumber: "CAL-001",
    description: "Disaster response and recovery vessel",
  },
  {
    id: "ship-010",
    name: "Solar Flare",
    class: 3,
    hullNumber: "SOL-001",
    description: "Energy research platform",
  },
  {
    id: "ship-011",
    name: "Rust Bucket",
    class: 0,
    hullNumber: "RUS-001",
    description: "Maintenance and repair vessel",
  },
  {
    id: "ship-012",
    name: "Vanguard Prime",
    class: 6,
    hullNumber: "VAN-001",
    description: "Advanced tactical operations platform",
  },
  {
    id: "ship-013",
    name: "Lunar Echo",
    class: 2,
    hullNumber: "LUN-001",
    description: "Lunar operations specialist",
  },
  {
    id: "ship-014",
    name: "Iron Sovereign",
    class: 8,
    hullNumber: "IRO-001",
    description: "Heavy industrial operations vessel",
  },
  {
    id: "ship-015",
    name: "Nebula Nomad",
    class: 4,
    hullNumber: "NEB-001",
    description: "Deep space exploration platform",
  },
];

// Terminal data - each ship has 1-4 terminals
export const TERMINALS: Terminal[] = [
  // Aegis Refrain terminals
  {
    id: "term-001",
    shipId: "ship-001",
    type: "UHF",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-001",
    notes: "Primary communication terminal",
  },
  {
    id: "term-002",
    shipId: "ship-001",
    type: "X-Band",
    designation: "Terminal-B",
    status: "active",
    currentLeaseId: "lease-002",
    notes: "High-bandwidth data downlink",
  },
  {
    id: "term-003",
    shipId: "ship-001",
    type: "Ka-Band",
    designation: "Terminal-C",
    status: "maintenance",
    notes: "Scheduled maintenance until 2026-04-15",
  },

  // Void Skimmer terminals
  {
    id: "term-004",
    shipId: "ship-002",
    type: "VHF",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-003",
    notes: "Primary uplink",
  },
  {
    id: "term-005",
    shipId: "ship-002",
    type: "UHF",
    designation: "Terminal-B",
    status: "standby",
    notes: "Backup communication",
  },

  // Harvester of Stars terminals
  {
    id: "term-006",
    shipId: "ship-003",
    type: "X-Band",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-004",
    notes: "Cargo manifest transmission",
  },
  {
    id: "term-007",
    shipId: "ship-003",
    type: "Ka-Band",
    designation: "Terminal-B",
    status: "active",
    currentLeaseId: "lease-005",
    notes: "Real-time telemetry",
  },
  {
    id: "term-008",
    shipId: "ship-003",
    type: "UHF",
    designation: "Terminal-C",
    status: "inactive",
    notes: "Decommissioned 2025-12-01",
  },
  {
    id: "term-009",
    shipId: "ship-003",
    type: "VHF",
    designation: "Terminal-D",
    status: "active",
    currentLeaseId: "lease-006",
    notes: "Emergency backup",
  },

  // Silent Prowler terminals
  {
    id: "term-010",
    shipId: "ship-004",
    type: "UHF",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-007",
    notes: "Encrypted communications",
  },
  {
    id: "term-011",
    shipId: "ship-004",
    type: "X-Band",
    designation: "Terminal-B",
    status: "standby",
    notes: "High-security backup",
  },

  // Titan's Reach terminals
  {
    id: "term-012",
    shipId: "ship-005",
    type: "Ka-Band",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-008",
    notes: "Command center primary link",
  },
  {
    id: "term-013",
    shipId: "ship-005",
    type: "X-Band",
    designation: "Terminal-B",
    status: "active",
    currentLeaseId: "lease-009",
    notes: "Tactical operations",
  },
  {
    id: "term-014",
    shipId: "ship-005",
    type: "VHF",
    designation: "Terminal-C",
    status: "active",
    currentLeaseId: "lease-010",
    notes: "Fleet coordination",
  },
  {
    id: "term-015",
    shipId: "ship-005",
    type: "UHF",
    designation: "Terminal-D",
    status: "active",
    currentLeaseId: "lease-011",
    notes: "Emergency broadcast",
  },

  // Neon Dragonfly terminals
  {
    id: "term-016",
    shipId: "ship-006",
    type: "VHF",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-012",
    notes: "Scout telemetry",
  },

  // Gilded Horizon terminals
  {
    id: "term-017",
    shipId: "ship-007",
    type: "X-Band",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-013",
    notes: "Diplomatic communications",
  },
  {
    id: "term-018",
    shipId: "ship-007",
    type: "Ka-Band",
    designation: "Terminal-B",
    status: "active",
    currentLeaseId: "lease-014",
    notes: "Data exchange",
  },

  // Obsidian Maw terminals
  {
    id: "term-019",
    shipId: "ship-008",
    type: "X-Band",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-015",
    notes: "Combat operations",
  },
  {
    id: "term-020",
    shipId: "ship-008",
    type: "UHF",
    designation: "Terminal-B",
    status: "active",
    currentLeaseId: "lease-016",
    notes: "Tactical coordination",
  },

  // Calamity's Wake terminals
  {
    id: "term-021",
    shipId: "ship-009",
    type: "Ka-Band",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-017",
    notes: "Emergency response coordination",
  },
  {
    id: "term-022",
    shipId: "ship-009",
    type: "VHF",
    designation: "Terminal-B",
    status: "active",
    currentLeaseId: "lease-018",
    notes: "Medical and rescue ops",
  },

  // Solar Flare terminals
  {
    id: "term-023",
    shipId: "ship-010",
    type: "X-Band",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-019",
    notes: "Energy research data",
  },
  {
    id: "term-024",
    shipId: "ship-010",
    type: "Ka-Band",
    designation: "Terminal-B",
    status: "maintenance",
    notes: "Calibration in progress",
  },

  // Rust Bucket terminals
  {
    id: "term-025",
    shipId: "ship-011",
    type: "UHF",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-020",
    notes: "Maintenance coordination",
  },

  // Vanguard Prime terminals
  {
    id: "term-026",
    shipId: "ship-012",
    type: "X-Band",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-021",
    notes: "Advanced tactical ops",
  },
  {
    id: "term-027",
    shipId: "ship-012",
    type: "Ka-Band",
    designation: "Terminal-B",
    status: "active",
    currentLeaseId: "lease-022",
    notes: "Real-time analysis",
  },

  // Lunar Echo terminals
  {
    id: "term-028",
    shipId: "ship-013",
    type: "VHF",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-023",
    notes: "Lunar surface operations",
  },
  {
    id: "term-029",
    shipId: "ship-013",
    type: "UHF",
    designation: "Terminal-B",
    status: "standby",
    notes: "Backup lunar link",
  },

  // Iron Sovereign terminals
  {
    id: "term-030",
    shipId: "ship-014",
    type: "X-Band",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-024",
    notes: "Industrial operations",
  },
  {
    id: "term-031",
    shipId: "ship-014",
    type: "Ka-Band",
    designation: "Terminal-B",
    status: "active",
    currentLeaseId: "lease-025",
    notes: "Production monitoring",
  },

  // Nebula Nomad terminals
  {
    id: "term-032",
    shipId: "ship-015",
    type: "Ka-Band",
    designation: "Terminal-A",
    status: "active",
    currentLeaseId: "lease-026",
    notes: "Deep space exploration",
  },
];

// Lease data with phases
export const LEASES: SatelliteLease[] = [
  {
    id: "lease-001",
    terminalId: "term-001",
    satelliteName: "COMSAT-1",
    txDataRate: 50,
    rxDataRate: 75,
    startDate: "2025-01-15",
    endDate: "2026-12-31",
    phases: [
      {
        id: "phase-001-1",
        leaseId: "lease-001",
        name: "Phase 1: Initial Setup",
        startDate: "2025-01-15",
        endDate: "2025-06-30",
        description: "System calibration and validation",
      },
      {
        id: "phase-001-2",
        leaseId: "lease-001",
        name: "Phase 2: Full Operations",
        startDate: "2025-07-01",
        endDate: "2026-12-31",
        txDataRate: 60,
        rxDataRate: 85,
        description: "Full operational capacity",
      },
    ],
    notes: "Primary communication satellite. Monitor signal strength daily.",
    createdAt: "2025-01-10",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-002",
    terminalId: "term-002",
    satelliteName: "DATASAT-2",
    txDataRate: 100,
    rxDataRate: 150,
    startDate: "2025-03-01",
    endDate: "2027-02-28",
    phases: [
      {
        id: "phase-002-1",
        leaseId: "lease-002",
        name: "Phase 1: Testing",
        startDate: "2025-03-01",
        endDate: "2025-08-31",
        description: "High-bandwidth testing phase",
      },
      {
        id: "phase-002-2",
        leaseId: "lease-002",
        name: "Phase 2: Production",
        startDate: "2025-09-01",
        endDate: "2027-02-28",
        txDataRate: 120,
        rxDataRate: 180,
        description: "Full production operations",
      },
    ],
    notes: "High-bandwidth downlink. Requires daily monitoring.",
    createdAt: "2025-02-20",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-003",
    terminalId: "term-004",
    satelliteName: "SCOUT-1",
    txDataRate: 25,
    rxDataRate: 40,
    startDate: "2025-06-01",
    endDate: "2026-05-31",
    phases: [
      {
        id: "phase-003-1",
        leaseId: "lease-003",
        name: "Phase 1: Reconnaissance",
        startDate: "2025-06-01",
        endDate: "2026-05-31",
        description: "Scout telemetry collection",
      },
    ],
    notes: "Scout vessel communications. Low-bandwidth operations.",
    createdAt: "2025-05-15",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-004",
    terminalId: "term-006",
    satelliteName: "CARGO-1",
    txDataRate: 75,
    rxDataRate: 100,
    startDate: "2025-02-01",
    endDate: "2027-01-31",
    phases: [
      {
        id: "phase-004-1",
        leaseId: "lease-004",
        name: "Phase 1: Cargo Tracking",
        startDate: "2025-02-01",
        endDate: "2027-01-31",
        description: "Cargo manifest and tracking",
      },
    ],
    notes: "Cargo vessel operations. Real-time manifest transmission.",
    createdAt: "2025-01-20",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-005",
    terminalId: "term-007",
    satelliteName: "TELEMETRY-1",
    txDataRate: 50,
    rxDataRate: 80,
    startDate: "2025-04-01",
    endDate: "2026-09-30",
    phases: [
      {
        id: "phase-005-1",
        leaseId: "lease-005",
        name: "Phase 1: Real-time Telemetry",
        startDate: "2025-04-01",
        endDate: "2026-09-30",
        description: "Continuous telemetry stream",
      },
    ],
    notes: "Real-time vessel telemetry. Critical for operations.",
    createdAt: "2025-03-25",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-006",
    terminalId: "term-009",
    satelliteName: "BACKUP-1",
    txDataRate: 30,
    rxDataRate: 50,
    startDate: "2025-05-01",
    endDate: "2026-04-30",
    phases: [
      {
        id: "phase-006-1",
        leaseId: "lease-006",
        name: "Phase 1: Emergency Backup",
        startDate: "2025-05-01",
        endDate: "2026-04-30",
        description: "Emergency backup communications",
      },
    ],
    notes: "Emergency backup only. Activate if primary fails.",
    createdAt: "2025-04-10",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-007",
    terminalId: "term-010",
    satelliteName: "SECURE-1",
    txDataRate: 40,
    rxDataRate: 60,
    startDate: "2025-07-01",
    endDate: "2027-06-30",
    phases: [
      {
        id: "phase-007-1",
        leaseId: "lease-007",
        name: "Phase 1: Encrypted Ops",
        startDate: "2025-07-01",
        endDate: "2027-06-30",
        description: "Encrypted communications channel",
      },
    ],
    notes: "Encrypted communications. High security requirements.",
    createdAt: "2025-06-15",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-008",
    terminalId: "term-012",
    satelliteName: "COMMAND-1",
    txDataRate: 200,
    rxDataRate: 250,
    startDate: "2024-01-01",
    endDate: "2027-12-31",
    phases: [
      {
        id: "phase-008-1",
        leaseId: "lease-008",
        name: "Phase 1: Command Center",
        startDate: "2024-01-01",
        endDate: "2027-12-31",
        description: "Primary command center link",
      },
    ],
    notes: "Flagship command center. Critical infrastructure.",
    createdAt: "2023-12-01",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-009",
    terminalId: "term-013",
    satelliteName: "TACTICAL-1",
    txDataRate: 150,
    rxDataRate: 200,
    startDate: "2024-06-01",
    endDate: "2027-05-31",
    phases: [
      {
        id: "phase-009-1",
        leaseId: "lease-009",
        name: "Phase 1: Tactical Ops",
        startDate: "2024-06-01",
        endDate: "2027-05-31",
        description: "Tactical operations coordination",
      },
    ],
    notes: "Tactical operations. Real-time coordination required.",
    createdAt: "2024-05-15",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-010",
    terminalId: "term-014",
    satelliteName: "FLEET-1",
    txDataRate: 100,
    rxDataRate: 150,
    startDate: "2024-09-01",
    endDate: "2027-08-31",
    phases: [
      {
        id: "phase-010-1",
        leaseId: "lease-010",
        name: "Phase 1: Fleet Coordination",
        startDate: "2024-09-01",
        endDate: "2027-08-31",
        description: "Fleet-wide coordination",
      },
    ],
    notes: "Fleet coordination satellite. Maintains fleet cohesion.",
    createdAt: "2024-08-20",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-011",
    terminalId: "term-015",
    satelliteName: "EMERGENCY-1",
    txDataRate: 50,
    rxDataRate: 75,
    startDate: "2024-12-01",
    endDate: "2027-11-30",
    phases: [
      {
        id: "phase-011-1",
        leaseId: "lease-011",
        name: "Phase 1: Emergency Broadcast",
        startDate: "2024-12-01",
        endDate: "2027-11-30",
        description: "Emergency broadcast capability",
      },
    ],
    notes: "Emergency broadcast system. Always operational.",
    createdAt: "2024-11-10",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-012",
    terminalId: "term-016",
    satelliteName: "SCOUT-2",
    txDataRate: 20,
    rxDataRate: 35,
    startDate: "2025-08-01",
    endDate: "2026-07-31",
    phases: [
      {
        id: "phase-012-1",
        leaseId: "lease-012",
        name: "Phase 1: Scout Telemetry",
        startDate: "2025-08-01",
        endDate: "2026-07-31",
        description: "Scout vessel telemetry",
      },
    ],
    notes: "Scout telemetry collection. Low bandwidth.",
    createdAt: "2025-07-15",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-013",
    terminalId: "term-017",
    satelliteName: "DIPLOMAT-1",
    txDataRate: 60,
    rxDataRate: 90,
    startDate: "2025-09-01",
    endDate: "2027-08-31",
    phases: [
      {
        id: "phase-013-1",
        leaseId: "lease-013",
        name: "Phase 1: Diplomatic Comms",
        startDate: "2025-09-01",
        endDate: "2027-08-31",
        description: "Diplomatic communications",
      },
    ],
    notes: "Diplomatic vessel communications. Secure channel.",
    createdAt: "2025-08-20",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-014",
    terminalId: "term-018",
    satelliteName: "DATA-EXCHANGE-1",
    txDataRate: 80,
    rxDataRate: 120,
    startDate: "2025-10-01",
    endDate: "2027-09-30",
    phases: [
      {
        id: "phase-014-1",
        leaseId: "lease-014",
        name: "Phase 1: Data Exchange",
        startDate: "2025-10-01",
        endDate: "2027-09-30",
        description: "High-speed data exchange",
      },
    ],
    notes: "Data exchange operations. High bandwidth required.",
    createdAt: "2025-09-15",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-015",
    terminalId: "term-019",
    satelliteName: "COMBAT-1",
    txDataRate: 180,
    rxDataRate: 220,
    startDate: "2024-03-01",
    endDate: "2027-02-28",
    phases: [
      {
        id: "phase-015-1",
        leaseId: "lease-015",
        name: "Phase 1: Combat Ops",
        startDate: "2024-03-01",
        endDate: "2027-02-28",
        description: "Combat operations support",
      },
    ],
    notes: "Combat operations. High priority. Always active.",
    createdAt: "2024-02-10",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-016",
    terminalId: "term-020",
    satelliteName: "TACTICAL-2",
    txDataRate: 120,
    rxDataRate: 160,
    startDate: "2024-07-01",
    endDate: "2027-06-30",
    phases: [
      {
        id: "phase-016-1",
        leaseId: "lease-016",
        name: "Phase 1: Tactical Coord",
        startDate: "2024-07-01",
        endDate: "2027-06-30",
        description: "Tactical coordination",
      },
    ],
    notes: "Tactical coordination satellite. Real-time ops.",
    createdAt: "2024-06-20",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-017",
    terminalId: "term-021",
    satelliteName: "RESCUE-1",
    txDataRate: 100,
    rxDataRate: 140,
    startDate: "2025-11-01",
    endDate: "2027-10-31",
    phases: [
      {
        id: "phase-017-1",
        leaseId: "lease-017",
        name: "Phase 1: Emergency Response",
        startDate: "2025-11-01",
        endDate: "2027-10-31",
        description: "Emergency response coordination",
      },
    ],
    notes: "Emergency response operations. Always ready.",
    createdAt: "2025-10-15",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-018",
    terminalId: "term-022",
    satelliteName: "MEDICAL-1",
    txDataRate: 70,
    rxDataRate: 110,
    startDate: "2025-12-01",
    endDate: "2027-11-30",
    phases: [
      {
        id: "phase-018-1",
        leaseId: "lease-018",
        name: "Phase 1: Medical Ops",
        startDate: "2025-12-01",
        endDate: "2027-11-30",
        description: "Medical and rescue operations",
      },
    ],
    notes: "Medical and rescue operations. Critical service.",
    createdAt: "2025-11-10",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-019",
    terminalId: "term-023",
    satelliteName: "RESEARCH-1",
    txDataRate: 90,
    rxDataRate: 130,
    startDate: "2025-01-01",
    endDate: "2026-12-31",
    phases: [
      {
        id: "phase-019-1",
        leaseId: "lease-019",
        name: "Phase 1: Energy Research",
        startDate: "2025-01-01",
        endDate: "2026-12-31",
        description: "Energy research data transmission",
      },
    ],
    notes: "Energy research platform. Continuous data stream.",
    createdAt: "2024-12-15",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-020",
    terminalId: "term-025",
    satelliteName: "MAINTENANCE-1",
    txDataRate: 40,
    rxDataRate: 60,
    startDate: "2025-02-15",
    endDate: "2026-02-14",
    phases: [
      {
        id: "phase-020-1",
        leaseId: "lease-020",
        name: "Phase 1: Maintenance Ops",
        startDate: "2025-02-15",
        endDate: "2026-02-14",
        description: "Maintenance coordination",
      },
    ],
    notes: "Maintenance vessel operations. Coordination link.",
    createdAt: "2025-01-30",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-021",
    terminalId: "term-026",
    satelliteName: "ADVANCED-1",
    txDataRate: 160,
    rxDataRate: 200,
    startDate: "2024-04-01",
    endDate: "2027-03-31",
    phases: [
      {
        id: "phase-021-1",
        leaseId: "lease-021",
        name: "Phase 1: Advanced Tactics",
        startDate: "2024-04-01",
        endDate: "2027-03-31",
        description: "Advanced tactical operations",
      },
    ],
    notes: "Advanced tactical platform. High priority.",
    createdAt: "2024-03-15",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-022",
    terminalId: "term-027",
    satelliteName: "ANALYSIS-1",
    txDataRate: 140,
    rxDataRate: 180,
    startDate: "2024-05-01",
    endDate: "2027-04-30",
    phases: [
      {
        id: "phase-022-1",
        leaseId: "lease-022",
        name: "Phase 1: Real-time Analysis",
        startDate: "2024-05-01",
        endDate: "2027-04-30",
        description: "Real-time analysis and processing",
      },
    ],
    notes: "Real-time analysis platform. Continuous operations.",
    createdAt: "2024-04-20",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-023",
    terminalId: "term-028",
    satelliteName: "LUNAR-1",
    txDataRate: 55,
    rxDataRate: 85,
    startDate: "2025-03-15",
    endDate: "2026-03-14",
    phases: [
      {
        id: "phase-023-1",
        leaseId: "lease-023",
        name: "Phase 1: Lunar Operations",
        startDate: "2025-03-15",
        endDate: "2026-03-14",
        description: "Lunar surface operations support",
      },
    ],
    notes: "Lunar operations specialist. Surface coordination.",
    createdAt: "2025-02-28",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-024",
    terminalId: "term-030",
    satelliteName: "INDUSTRIAL-1",
    txDataRate: 110,
    rxDataRate: 160,
    startDate: "2024-08-01",
    endDate: "2027-07-31",
    phases: [
      {
        id: "phase-024-1",
        leaseId: "lease-024",
        name: "Phase 1: Industrial Ops",
        startDate: "2024-08-01",
        endDate: "2027-07-31",
        description: "Industrial operations monitoring",
      },
    ],
    notes: "Industrial operations platform. Production critical.",
    createdAt: "2024-07-15",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-025",
    terminalId: "term-031",
    satelliteName: "PRODUCTION-1",
    txDataRate: 130,
    rxDataRate: 180,
    startDate: "2024-10-01",
    endDate: "2027-09-30",
    phases: [
      {
        id: "phase-025-1",
        leaseId: "lease-025",
        name: "Phase 1: Production Monitor",
        startDate: "2024-10-01",
        endDate: "2027-09-30",
        description: "Production monitoring and control",
      },
    ],
    notes: "Production monitoring satellite. Real-time control.",
    createdAt: "2024-09-20",
    updatedAt: "2026-03-16",
  },
  {
    id: "lease-026",
    terminalId: "term-032",
    satelliteName: "EXPLORER-1",
    txDataRate: 95,
    rxDataRate: 140,
    startDate: "2025-04-15",
    endDate: "2027-04-14",
    phases: [
      {
        id: "phase-026-1",
        leaseId: "lease-026",
        name: "Phase 1: Deep Space Exploration",
        startDate: "2025-04-15",
        endDate: "2027-04-14",
        description: "Deep space exploration support",
      },
    ],
    notes: "Deep space exploration platform. Long-range ops.",
    createdAt: "2025-03-30",
    updatedAt: "2026-03-16",
  },
];

// Operational notes
export const OPERATIONAL_NOTES: OperationalNote[] = [
  {
    id: "note-001",
    terminalId: "term-001",
    type: "maintenance",
    title: "Scheduled maintenance completed",
    content: "Annual calibration and signal strength verification completed successfully.",
    severity: "low",
    createdAt: "2026-03-10",
    createdBy: "Operator-001",
    resolvedAt: "2026-03-10",
  },
  {
    id: "note-002",
    terminalId: "term-002",
    type: "observation",
    title: "Signal strength trending upward",
    content: "DATASAT-2 signal strength has improved 15% over the last week. Likely due to orbital adjustment.",
    severity: "low",
    createdAt: "2026-03-14",
    createdBy: "Operator-002",
  },
  {
    id: "note-003",
    terminalId: "term-003",
    type: "maintenance",
    title: "Ka-Band terminal maintenance scheduled",
    content: "Scheduled maintenance window: 2026-04-01 to 2026-04-15. Will impact COMSAT operations.",
    severity: "medium",
    createdAt: "2026-03-01",
    createdBy: "Maintenance-Team",
  },
  {
    id: "note-004",
    terminalId: "term-010",
    type: "issue",
    title: "Encryption key rotation needed",
    content: "Security audit flagged need for encryption key rotation. Schedule for next maintenance window.",
    severity: "high",
    createdAt: "2026-03-12",
    createdBy: "Security-Officer",
  },
  {
    id: "note-005",
    terminalId: "term-012",
    type: "observation",
    title: "Command center link stability excellent",
    content: "COMMAND-1 satellite link showing 99.97% uptime over last 30 days. Excellent performance.",
    severity: "low",
    createdAt: "2026-03-15",
    createdBy: "Operator-001",
  },
];
